name: Daily Weather Check

on:
  schedule:
    # Runs at 6 PM every day
    - cron: "0 22 * * *"
  push:
    branches:
      - main  # Change this to the branch you want to run the workflow on push

jobs:
  weather-check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Run weather check script
      env:
        EMAIL: ${{ secrets.EMAIL }}
        APP_PASSWORD: ${{ secrets.APP_PASSWORD }}
        API_KEY: ${{ secrets.API_KEY }}
        LATITUDE: ${{ secrets.LATITUDE }}
        LONGITUDE: ${{ secrets.LONGITUDE }}
      run: python rain-tomorrow.py
